// page meta actions
export const PAGE_META_REQUEST = 'PAGE_META_REQUEST';
export const PAGE_META_SUCCESS = 'PAGE_META_SUCCESS';
export const PAGE_META_FAILURE = 'PAGE_META_FAILURE';

// page actions
export const PAGE_REQUEST = 'PAGE_REQUEST';
export const PAGE_SUCCESS = 'PAGE_SUCCESS';
export const PAGE_FAILURE = 'PAGE_FAILURE';

// element actions
export const RENDERABLE_ELEMENTS_CREATED = 'RENDERABLE_ELEMENTS_CREATED';
export const ELEMENT_SELECTED = 'ELEMENT_SELECTED';
export const ELEMENT_DESELECTED = 'ELEMENT_DESELECTED';
export const ELEMENT_UPDATED = 'ELEMENT_UPDATED';
export const ELEMENT_CREATE_FROM_TYPE = 'ELEMENT_CREATE_FROM_TYPE';
export const ELEMENT_CREATED = 'ELEMENT_CREATED';
export const ELEMENT_ADDED_TO_PAGE = 'ELEMENT_ADDED_TO_PAGE';